### PR TITLE
Fix issue when sum of all weights is 0

### PR DESCRIPTION
**Pull request by nathanhoel**
Sets MLE to 0 when the sum of all weights is 0

### CODE REVIEW

**Comment by yongjun21** [comment]
This check should be implemented in userland

**Comment by nathanhoel** [comment]
I would make one last attempt to convince you.
My argument would be that calculating the weights is non-trivial. I am not sure why the userland code would want to duplicate this part of the algorithm just to detect if the sums will be zero.

**Comment by yongjun21** [comment]
I have mistaken in thinking that the reason for sum of weights to be zero because user has w to zero for every points initial. Though it will be more illuminating to show how certain initial conditions can lead to sum of weights to collapse to zero. And also justify why setting mle to zero when that happen is a good default

**Comment by nathanhoel** [comment]
This happens when the slope of the linear regression is near 0 (flat) so that the sum of the weights tends towards zero as well. The problem happens when `robust` mode is turned on which performs multiple iterations and has a smoothing effect on the regression line.

The reason setting the `mle` to zero is the right answer is because the `mle` is used to fit the curve/slope to data and since all points are essentially trending towards the same value they should all have the same weight and value.

Indeed using an `mle` of zero produces the right answer as well because we had essentially a flat line with no slope for our scatter plot and loess would predict a flat line with no slope.

I will also mention again, it is non-trivial to calculate whether the slope of the regression will be flat though, so having the user do it is essentially the same as rewriting most of this library. This is especially true because loess locally estimates the predictions, so again it is essential that the loess algorithm incorporate this edge case and not leave it up to the user.

**Comment by scott-lindenberg** [comment]
I ran into this issue as well.  Here is the updated code change:

const sumWeights = _mathjs2.default.sum(weights[idx]);
const mle = sumWeights === 0 ? 0 : _mathjs2.default.multiply(_this3.y, weights[idx]) / sumWeights;

**Review by yongjun21 — APPROVED** [review]

**Pull request merged**
